#!/bin/bash

./compile
echo "Ready. Deploying peers {1,2,3,4,5}"

echo "Random files..."
./randomfile 1MB s1.txt
./randomfile 2MB s2.txt
./randomfile 3MB s3.txt
./randomfile 4MB s4.txt
./randomfile 5MB s5.txt

echo "Launch peers..."
(./launch-peer 1 >/dev/null 2>&1) &
(./launch-peer 2 >/dev/null 2>&1) &
(./launch-peer 3 >/dev/null 2>&1) &
(./launch-peer 4 >/dev/null 2>&1) &
(./launch-peer 5 >/dev/null 2>&1) &

sleep 1.5

echo "Reclaims..."
./reclaim 1 12000
./reclaim 2 11000
./reclaim 3 15000
./reclaim 4 11000
./reclaim 5 9000

echo "Backups..."
./backup 1 s1.txt 3
./backup 2 s2.txt 4
./backup 3 s3.txt 2
./backup 4 s4.txt 1
./backup 5 s5.txt 1

echo "Deployed backup requests. Proceed when finished."
read

echo "Restores..."
./restore 1 s1.txt
./restore 2 s2.txt
./restore 3 s3.txt
./restore 4 s4.txt
./restore 5 s5.txt

echo "Deployed restore requests. Proceed when finished."
read

echo "=== COMPARISONS ==="
cmp s1.txt /tmp/dbs/peer-1/restored/s1.txt || echo "s1.txt differs"
cmp s2.txt /tmp/dbs/peer-2/restored/s2.txt || echo "s2.txt differs"
cmp s3.txt /tmp/dbs/peer-3/restored/s3.txt || echo "s3.txt differs"
cmp s4.txt /tmp/dbs/peer-4/restored/s4.txt || echo "s4.txt differs"
cmp s5.txt /tmp/dbs/peer-5/restored/s5.txt || echo "s5.txt differs"

echo "Finished comparisons. Proceed to delete all files."
read

echo "Deletes..."
./delete 1 s1.txt
./delete 2 s2.txt
./delete 3 s3.txt
./delete 4 s4.txt
./delete 5 s5.txt

echo "Finished deletes. Proceed to verify states."
read

echo "STATE 1:"
./state 1

echo "STATE 2:"
./state 2

echo "STATE 3:"
./state 3

echo "STATE 4:"
./state 4

echo "STATE 5:"
./state 5
