#!/bin/bash

./compile && rm -rf /tmp/dbs
echo "Ready..."
read

# Backup 500KB file
fallocate -l 500000 r.txt
java -cp . dbs.TestApp 1 BACKUP r.txt 3
sleep 2
echo "Ready..."
read

# Reclaim 200KB from peer 2, initiating PUTCHUNK for each chunk.
java -cp . dbs.TestApp 2 RECLAIM 200

# The first few PUTCHUNKs will fail, but after this they will succeed.
sleep 1.5
java -cp . dbs.TestApp 2 RECLAIM 5000
