#!/bin/bash

# Arg#1 Launch how many echo clients?
clients="$1"

# Arg#2 Launch how many echo servers?
servers="$2"

# Arg#3 Launch on which multicast port?
mport="$3"

# Arg#4 Launch on which multicast address?
maddress="$4"

# Default multicast port
if [ -z "$3" ]
then
  mport="29500"
fi

# Default multicast address
if [ -z "$4" ]
then
  maddress="237.0.0.1"
fi

# Reset test directory
mkdir -p test
rm -rf test/*

# Launch clients
for i in `seq 1 $servers`;
do
  java -cp bin echo.Server "$mport" "$maddress" "test/d$i" &
  sleep 0.02s
done

# Wait before launching clients
sleep 1s

for i in `seq 1 $clients`;
do
  java -cp bin echo.Client "$mport" "$maddress" "file-$i" &
  # Sleep between clients?
  # sleep 0.02s
done

# Wait for all
wait
